import '../models/station.dart';

class MelbourneGtfsService {
  static final List<Station> melbourneHubStations = [
    const Station(
      id: 'st_flinders',
      stopId: '19842',
      name: 'Flinders Street Station',
      code: 'FSS',
      lat: -37.8183,
      lon: 144.9671,
      suburb: 'Melbourne CBD',
      zone: 'Zone 1',
      isCityLoop: true,
      routes: [],
    ),
    const Station(
      id: 'st_southern_cross',
      stopId: '22180',
      name: 'Southern Cross Station',
      code: 'SSS',
      lat: -37.8185,
      lon: 144.9525,
      suburb: 'Docklands / CBD',
      zone: 'Zone 1',
      isCityLoop: true,
      routes: [],
    ),
    const Station(
      id: 'st_melbourne_central',
      stopId: '19843',
      name: 'Melbourne Central Station',
      code: 'MCE',
      lat: -37.8102,
      lon: 144.9628,
      suburb: 'Melbourne CBD',
      zone: 'Zone 1',
      isCityLoop: true,
      routes: [],
    ),
    const Station(
      id: 'st_parliament',
      stopId: '19844',
      name: 'Parliament Station',
      code: 'PAR',
      lat: -37.8113,
      lon: 144.9729,
      suburb: 'Melbourne CBD',
      zone: 'Zone 1',
      isCityLoop: true,
      routes: [],
    ),
    const Station(
      id: 'st_richmond',
      stopId: '19845',
      name: 'Richmond Station',
      code: 'RMD',
      lat: -37.8240,
      lon: 144.9896,
      suburb: 'Richmond',
      zone: 'Zone 1',
      isCityLoop: false,
      routes: [],
    ),
    const Station(
      id: 'st_north_melbourne',
      stopId: '19846',
      name: 'North Melbourne Station',
      code: 'NMS',
      lat: -37.8073,
      lon: 144.9427,
      suburb: 'West Melbourne',
      zone: 'Zone 1',
      isCityLoop: false,
      routes: [],
    ),
    const Station(
      id: 'st_footscray',
      stopId: '19982',
      name: 'Footscray Station',
      code: 'FSY',
      lat: -37.8013,
      lon: 144.9030,
      suburb: 'Footscray',
      zone: 'Zone 1',
      isCityLoop: false,
      routes: [],
    ),
    const Station(
      id: 'st_box_hill',
      stopId: '19850',
      name: 'Box Hill Station',
      code: 'BOX',
      lat: -37.8190,
      lon: 145.1227,
      suburb: 'Box Hill',
      zone: 'Zone 2',
      isCityLoop: false,
      routes: [],
    ),
    const Station(
      id: 'st_dandenong',
      stopId: '19855',
      name: 'Dandenong Station',
      code: 'DNG',
      lat: -38.0001,
      lon: 145.2155,
      suburb: 'Dandenong',
      zone: 'Zone 2',
      isCityLoop: false,
      routes: [],
    ),
    const Station(
      id: 'st_geelong',
      stopId: '20291',
      name: 'Geelong Station',
      code: 'GLG',
      lat: -38.1448,
      lon: 144.3541,
      suburb: 'Geelong',
      zone: 'Regional (Zone 4)',
      isCityLoop: false,
      routes: [],
    ),
  ];
}
