#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/charliecafici/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/charliecafici/Documents/GitHub/TransitApp"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/charliecafici/Documents/GitHub/TransitApp/macos/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/charliecafici/Documents/GitHub/TransitApp/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=2.8.4"
export "FLUTTER_BUILD_NUMBER=2.8.4"
export "DART_DEFINES=RkxVVFRFUl9CVUlMRF9OQU1FPTIuOC40,RkxVVFRFUl9WRVJTSU9OPTMuNDcuMA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NGNmMjQxNjQyNg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NWY3NzYyNTY3Mw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy4w"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/charliecafici/Documents/GitHub/TransitApp/.dart_tool/package_config.json"
